# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{SgfParser}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aldric Giacomoni"]
  s.date = %q{2010-04-30}
  s.description = %q{SGFParser is a library that parses and saves SGF (Smart Game Format) files.}
  s.email = %q{aldric@trevoke.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "SgfParser.gemspec",
     "VERSION",
     "lib/sgf/parser/node.rb",
     "lib/sgf/parser/properties.rb",
     "lib/sgf/parser/tree.rb",
     "lib/sgf/parser/tree_parse.rb",
     "lib/sgf/sgf_indent.rb",
     "lib/sgf_parser.rb",
     "sample_sgf/ff4_ex.sgf",
     "sample_sgf/redrose-tartrate.sgf",
     "sample_usage/parsing_files.rb",
     "spec/node_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/tree_spec.rb",
     "tryme.rb"
  ]
  s.homepage = %q{http://github.com/Trevoke/SGFParser}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A library for working with SGF files.}
  s.test_files = [
    "spec/node_spec.rb",
     "spec/spec_helper.rb",
     "spec/tree_parser_spec.rb",
     "spec/tree_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

